name: EthOS Config Manager
description: |
  UI for managing EthOS Configurations
version: 1.0.00
category: cryptocurrency
maintainer: Jamie Curnow <jc@jc21.com>
license: BSD
projectURL: https://github.com/jc21/ethos-config-manager
