name: Intense Coin
description: |
  Intense Coin Node
version: 1.0.0
category: cryptocurrency
maintainer: BBO <baseboxorg@outlook.com>
license: BSD
projectURL: https://github.com/baseboxorg/docker-intensecoind
