name: Juxtapose
description: |
  Get notified of events that you want to know about without being swamped in noise
version: 1.0.2
category: notifications
maintainer: Jamie Curnow <jc@jc21.com>
license: BSD
projectURL: https://github.com/jc21/juxtapose
